// Single source-of-truth loader for the parsed Excel dataset.
// JSON is generated by scripts/generate-company-data.mjs (npm run dev / npm run build).
import companyData from "./generated/company-data.json"
import type {
  CompanyDataset,
  CompanyRecord,
  MajorAnalytics,
  RegistrationStatus,
  SemesterCode,
} from "./types"
import { activeRegistrationSeed, toRegistrationRow } from "./activeRegistrations"
import { ACTIVE_FAIR } from "./fairConfig"
import { normalizeCompanyName, getCompanySlug } from "./companyNormalizer"
import { mapRawStatus } from "./statusMapping"

const dataset = companyData as unknown as CompanyDataset

export function getDataset(): CompanyDataset {
  return dataset
}

export function getAllCompanies(): CompanyRecord[] {
  return getCompaniesWithActiveRegistrationOverlay()
}

export function getMajorAnalytics(): MajorAnalytics[] {
  return dataset.majorAnalytics
}

export function getCompanyById(id: string): CompanyRecord | undefined {
  return getCompaniesWithActiveRegistrationOverlay().find((c) => c.id === id)
}

/**
 * Fall 2026 is the explicit active registration cycle. Excel fair sheets,
 * including S26_CF, are historical company intelligence and must not be
 * inferred as current registrations.
 */
export function getCurrentSemester(): SemesterCode {
  return ACTIVE_FAIR.code
}

export function getRegistrationCompanies(
  semester: SemesterCode = ACTIVE_FAIR.code,
): CompanyRecord[] {
  return getCompaniesWithActiveRegistrationOverlay().filter(
    (c) => c.currentRegistration?.semester === semester,
  )
}

export function getCompaniesWithActiveRegistrationOverlay(): CompanyRecord[] {
  const companies: CompanyRecord[] = dataset.companies.map((company) => ({
    ...company,
    currentRegistration: null,
    registrationHistory: { ...company.registrationHistory },
    sources: [...company.sources],
  }))

  for (const seed of activeRegistrationSeed) {
    const seedName = normalizeCompanyName(seed.companyName)
    const registration = toRegistrationRow(seed)
    let company = companies.find(
      (candidate) =>
        normalizeCompanyName(candidate.canonicalName) === seedName ||
        candidate.variants.some((variant) => normalizeCompanyName(variant) === seedName),
    )

    if (!company) {
      company = createCompanyFromSeed(seed.companyName)
      companies.push(company)
    }

    company.currentRegistration = registration
    company.registrationHistory[ACTIVE_FAIR.code] = registration
    company.sources = Array.from(
      new Set([...company.sources, `ActiveRegistrationSeed:${ACTIVE_FAIR.code}`]),
    )
    company.industry = company.industry ?? seed.industry
    company.industryTags = Array.from(new Set([...company.industryTags, seed.industry]))
    if (!company.variants.includes(seed.companyName)) {
      company.variants = [...company.variants, seed.companyName]
    }
  }

  return companies
}

function createCompanyFromSeed(companyName: string): CompanyRecord {
  return {
    id: getCompanySlug(companyName),
    canonicalName: companyName,
    variants: [companyName],
    sources: [`ActiveRegistrationSeed:${ACTIVE_FAIR.code}`],
    industry: null,
    industryTags: [],
    companyType: null,
    revenueMillionsUSD: null,
    marketCapBillionsUSD: null,
    employees: null,
    willingToSponsor: null,
    bachelorHires: null,
    masterHires: null,
    doctorateHires: null,
    totalHires: 0,
    hiringHistory: {},
    attendanceHistory: {},
    semestersAttended: [],
    packageHistory: {},
    currentRegistration: null,
    registrationHistory: {},
    relationship: {
      attendedPastFairs: false,
      outsideEngagement: false,
      fycfParticipant: false,
      alumniPresence: false,
      careerCenterPartner: false,
      coeDonor: false,
    },
    f25Selection: null,
    f25SortedHistory: null,
    f25Waitlist: null,
    majorBuckets: [],
  }
}

/**
 * Effective canonical status for a company in the current cycle. Uses the
 * registration sheet status first, then the F25 selection decision, then
 * defaults to "Pending".
 */
export function getEffectiveStatus(
  company: CompanyRecord,
  currentSemester: SemesterCode = ACTIVE_FAIR.code,
): RegistrationStatus {
  const reg =
    company.currentRegistration?.semester === currentSemester
      ? company.currentRegistration
      : undefined
  const fromReg = mapRawStatus(reg?.status)
  if (fromReg) return fromReg
  return "Pending"
}
