// Single source-of-truth loader for the parsed Excel dataset.
// JSON is generated by scripts/generate-company-data.mjs (npm run dev / npm run build).
import companyData from "./generated/company-data.json"
import type {
  CompanyDataset,
  CompanyRecord,
  MajorAnalytics,
  RegistrationStatus,
  SemesterCode,
} from "./types"
import { ACTIVE_FAIR } from "./fairConfig"
import { mapRawStatus } from "./statusMapping"

const dataset = companyData as unknown as CompanyDataset

export function getDataset(): CompanyDataset {
  return dataset
}

export function getAllCompanies(): CompanyRecord[] {
  return getCompaniesWithActiveRegistrationOverlay()
}

export function getMajorAnalytics(): MajorAnalytics[] {
  return dataset.majorAnalytics
}

export function getCompanyById(id: string): CompanyRecord | undefined {
  return getCompaniesWithActiveRegistrationOverlay().find((c) => c.id === id)
}

/**
 * Fall 2026 is the explicit active registration cycle. Excel fair sheets,
 * including S26_CF, are historical company intelligence and must not be
 * inferred as current registrations.
 */
export function getCurrentSemester(): SemesterCode {
  return ACTIVE_FAIR.code
}

export function getRegistrationCompanies(
  semester: SemesterCode = ACTIVE_FAIR.code,
): CompanyRecord[] {
  return getCompaniesWithActiveRegistrationOverlay().filter(
    (c) => c.currentRegistration?.semester === semester,
  )
}

export function getCompaniesWithActiveRegistrationOverlay(): CompanyRecord[] {
  return dataset.companies.map((company) => {
    let currentRegistration = company.currentRegistration ?? null
    // Generated JSON may still carry S26 as currentRegistration until regen; F26 is sheet-driven.
    if (ACTIVE_FAIR.code === "F26" && currentRegistration?.semester !== "F26") {
      currentRegistration = company.registrationHistory[ACTIVE_FAIR.code] ?? null
    }
    return {
      ...company,
      currentRegistration,
      registrationHistory: { ...company.registrationHistory },
      sources: [...company.sources],
    }
  })
}

/**
 * Effective canonical status for a company in the current cycle. Uses the
 * registration sheet status first, then the F25 selection decision, then
 * defaults to "Pending".
 */
export function getEffectiveStatus(
  company: CompanyRecord,
  currentSemester: SemesterCode = ACTIVE_FAIR.code,
): RegistrationStatus {
  const reg =
    company.currentRegistration?.semester === currentSemester
      ? company.currentRegistration
      : undefined
  const fromReg = mapRawStatus(reg?.status)
  if (fromReg) return fromReg
  return "Pending"
}
