// Single source-of-truth loader for the parsed Excel dataset.
// JSON is generated by scripts/generate-company-data.mjs (predev/prebuild).
import companyData from "./generated/company-data.json"
import type {
  CompanyDataset,
  CompanyRecord,
  MajorAnalytics,
  RegistrationStatus,
  SemesterCode,
} from "./types"
import { mapRawStatus } from "./statusMapping"

const dataset = companyData as unknown as CompanyDataset

export function getDataset(): CompanyDataset {
  return dataset
}

export function getAllCompanies(): CompanyRecord[] {
  return dataset.companies
}

export function getMajorAnalytics(): MajorAnalytics[] {
  return dataset.majorAnalytics
}

export function getCompanyById(id: string): CompanyRecord | undefined {
  return dataset.companies.find((c) => c.id === id)
}

/**
 * Companies relevant for the current Registrations view: those with a
 * registration record in the latest available semester.
 */
export function getCurrentSemester(): SemesterCode {
  // pick most recent semester that has any registration data
  for (let i = dataset.semesterOrder.length - 1; i >= 0; i--) {
    const sem = dataset.semesterOrder[i]
    if (dataset.companies.some((c) => c.registrationHistory[sem])) {
      return sem
    }
  }
  return "S26"
}

export function getRegistrationCompanies(
  semester: SemesterCode,
): CompanyRecord[] {
  return dataset.companies.filter((c) => Boolean(c.registrationHistory[semester]))
}

/**
 * Effective canonical status for a company in the current cycle. Uses the
 * registration sheet status first, then the F25 selection decision, then
 * defaults to "Pending".
 */
export function getEffectiveStatus(
  company: CompanyRecord,
  currentSemester: SemesterCode = "S26",
): RegistrationStatus {
  const reg = company.registrationHistory[currentSemester]
  const fromReg = mapRawStatus(reg?.status)
  if (fromReg) return fromReg
  const fromF25 = mapRawStatus(company.f25Selection?.decision)
  if (fromF25) return fromF25
  return "Pending"
}
